const defaultLocations = [
    {
        "name": "AltaMed Anaheim Medical",
        "company": "AltaMed",
        "lat": 33.853270,
        "lng": -117.920781,
        "addr": "1325 N Anaheim Blvd Anaheim",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical", "Dental", "PACE", "Urgent Care"]
    },
    {
    "name": "AltaMed Brady",
    "addr": "6201 Whittier Blvd, East Los Angeles, CA 90022",
    "company": "AltaMed",
    "cat": "Medical",
    "lat": 34.016495,
    "lng": -118.137016,
    "open": "08:00",
    "close": "17:00",
    "services": ["Medical"]
},
    {
        "name": "AltaMed Pasadena Del Mar",
        "addr": "3160 E Del Mar Blvd, Pasadena, CA 91107",
        "company": "AltaMed",
        "cat": "Medical",
        "lat": 34.141872,
        "lng": -118.08539,
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed William Mead",
        "addr": "268 E Bloom St, Los Angeles, CA 90012",
        "company": "AltaMed",
        "cat": "Medical",
        "lat": 34.063606,
        "lng": -118.229617,
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed Santa Ana Bristol",
        "addr": "2720 S Bristol St, Santa Ana, CA 92704",
        "company": "AltaMed",
        "cat": "Medical",
        "lat": 33.710369,
        "lng": -117.886182,
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed El Monte Valley",
        "addr": "10418 Valley Blvd, El Monte, CA 91731",
        "company": "AltaMed",
        "cat": "Medical",
        "lat": 34.076177,
        "lng": -118.045714,
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed Bell Gardens Viva Gold",
        "company": "AltaMed",
        "lat": 33.971512,
        "lng": -118.165710,
        "addr": "6811 Eastern Ave Bell Gardens",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical", "Dental"]
    },
    {
        "name": "AltaMed Bellflower Viva Gold",
        "company": "AltaMed",
        "lat": 33.901619,
        "lng": -118.115252,
        "addr": "10234 Rosecrans Ave Bellflower",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed Bellflower-Pharmacy",
        "company": "AltaMed",
        "lat": 33.902688,
        "lng": -118.140766,
        "addr": "9056 Rosecrans Ave Bellflower",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical", "Pharmacy"]
    },
    {
        "name": "AltaMed CHLA PODS 1-4",
        "company": "AltaMed",
        "lat": 34.097919,
        "lng": -118.290755,
        "addr": "4650 West Sunset Blvd. Los Angeles",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed Compton PACE",
        "company": "AltaMed",
        "lat": 33.888461,
        "lng": -118.195284,
        "addr": "2616 E Alondra Blvd Compton",
        "cat": "PACE",
        "open": "08:00",
        "close": "17:00",
        "services": ["PACE", "Medical"]
    },
    {
        "name": "AltaMed Corporate HQ",
        "company": "AltaMed",
        "lat": 34.007989,
        "lng": -118.155341,
        "addr": "2040 Camfield Ave",
        "cat": "Admin",
        "open": "08:00",
        "close": "17:00",
        "services": ["Corporate"]
    },
    {
        "name": "AltaMed East LA 1st Street",
        "company": "AltaMed",
        "lat": 34.044267,
        "lng": -118.211774,
        "addr": "2219 East 1st Street Los Angeles",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed East LA Boyle Heights",
        "company": "AltaMed",
        "lat": 34.024200,
        "lng": -118.187758,
        "addr": "3945 Whittier Blvd. Los Angeles",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical", "Dental", "Pharmacy"]
    },
    {
        "name": "AltaMed East LA Commerce",
        "company": "AltaMed",
        "lat": 34.019905,
        "lng": -118.153603,
        "addr": "5427 Whittier Blvd. Los Angeles",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical", "Dental"]
    },
    {
        "name": "AltaMed Ramona Gardens",
        "addr": "1424 Crusado Ln #168, Los Angeles, CA 90033",
        "company": "AltaMed",
        "cat": "Medical",
        "lat": 34.057659,
        "lng": -118.195155,
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed El Monte - Garvey Viva Gold",
        "company": "AltaMed",
        "lat": 34.062956,
        "lng": -118.048256,
        "addr": "10127 Garvey Ave El Monte",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed El Monte - Peck Rd",
        "company": "AltaMed",
        "lat": 34.073279,
        "lng": -118.024229,
        "addr": "3703 Peck Rd El Monte",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed El Monte - Santa Anita",
        "company": "AltaMed",
        "lat": 34.066280,
        "lng": -118.042205,
        "addr": "3208 Santa Anita Ave El Monte",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed Estrada Courts",
        "company": "AltaMed",
        "lat": 34.020853,
        "lng": -118.208152,
        "addr": "1305 S. Concord Street Los Angeles",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed Fair Oaks",
        "company": "AltaMed",
        "lat": 34.177574,
        "lng": -118.151049,
        "addr": "1855 N Fair Oaks Ave",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical", "Dental"]
    },
    {
        "name": "AltaMed Garden Grove",
        "company": "AltaMed",
        "lat": 33.777733,
        "lng": -117.915546,
        "addr": "12751 Harbor Blvd. Garden Grove",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical", "Dental"]
    },
    {
        "name": "AltaMed Goodrich",
        "company": "AltaMed",
        "lat": 34.018376,
        "lng": -118.153941,
        "addr": "972 Goodrich Blvd. Commerce",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed HP Medical (Rugby)",
        "company": "AltaMed",
        "lat": 33.979132,
        "lng": -118.226709,
        "addr": "6601 Rugby Ave",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed HP Medical (Slauson)",
        "company": "AltaMed",
        "lat": 33.988945,
        "lng": -118.236939,
        "addr": "1900 E Slauson Ave",
        "cat": "Medical",
        "open": "08:00",
        "close": "18:00",
        "services": ["Medical", "Dental", "Pharmacy"]
    },
    {
        "name": "AltaMed Huntington Beach - Main",
        "company": "AltaMed",
        "lat": 33.680153,
        "lng": -118.000353,
        "addr": "2100 Main St Huntington Beach",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed Huntington Beach - Newman",
        "company": "AltaMed",
        "lat": 33.705071,
        "lng": -117.988325,
        "addr": "8041 Newman Ave. Huntington Beach",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical", "Dental"]
    },
    {
        "name": "AltaMed Huntington Park Florence",
        "company": "AltaMed",
        "lat": 33.974617,
        "lng": -118.246133,
        "addr": "1542 E Florence Ave Los Angeles",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed Huntington Park Seville",
        "company": "AltaMed",
        "lat": 33.968758,
        "lng": -118.222610,
        "addr": "7705 Seville Ave Huntington Park",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical", "Dental"]
    },
    {
        "name": "AltaMed Indiana",
        "company": "AltaMed",
        "lat": 34.030042,
        "lng": -118.192119,
        "addr": "512 South Indiana St. Los Angeles",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed Inglewood PACE",
        "company": "AltaMed",
        "lat": 33.944499,
        "lng": -118.329024,
        "addr": "3310 W Century Blvd Inglewood",
        "cat": "PACE",
        "open": "08:00",
        "close": "17:00",
        "services": ["PACE", "Medical"]
    },
    {
        "name": "AltaMed Lake",
        "company": "AltaMed",
        "lat": 34.173473,
        "lng": -118.132284,
        "addr": "1595 N Lake Ave Pasadena",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed Lime",
        "company": "AltaMed",
        "lat": 34.148434,
        "lng": -117.993158,
        "addr": "513 Lime Ave Monrovia",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed Lincoln",
        "company": "AltaMed",
        "lat": 34.181036,
        "lng": -118.159986,
        "addr": "2059 Lincoln Ave Pasadena",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed Logistics Warehouse",
        "company": "AltaMed",
        "lat": 34.012115,
        "lng": -118.154397,
        "addr": "5550 Union Pacific Ave",
        "cat": "Admin",
        "open": "07:00",
        "close": "16:00",
        "services": ["Corporate"]
    },
    {
        "name": "AltaMed Lynwood PACE",
        "company": "AltaMed",
        "lat": 33.927324,
        "lng": -118.197854,
        "addr": "3820 MLK Jr. Blvd. Lynwood",
        "cat": "PACE",
        "open": "08:00",
        "close": "17:00",
        "services": ["PACE"]
    },
    {
        "name": "AltaMed Montana Admin",
        "company": "AltaMed",
        "lat": 34.181067,
        "lng": -118.160474,
        "addr": "455 Montana St Pasadena",
        "cat": "Admin",
        "open": "08:00",
        "close": "17:00",
        "services": ["Admin"]
    },
    {
        "name": "AltaMed Norwalk PACE",
        "company": "AltaMed",
        "lat": 33.902777,
        "lng": -118.087706,
        "addr": "11541 Rosecrans Ave Norwalk",
        "cat": "PACE",
        "open": "08:00",
        "close": "17:00",
        "services": ["PACE"]
    },
    {
        "name": "AltaMed Orange - Chapman",
        "company": "AltaMed",
        "lat": 33.787449,
        "lng": -117.810945,
        "addr": "4010 East Chapman Ave. Orange",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed Paramount - Paramount",
        "company": "AltaMed",
        "lat": 33.897990,
        "lng": -118.159895,
        "addr": "14906 Paramount Blvd Paramount",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed Pico Rivera - Passons",
        "company": "AltaMed",
        "lat": 33.984990,
        "lng": -118.085823,
        "addr": "6336 Passons Blvd. Pico Rivera",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed Pico Rivera - Washington",
        "company": "AltaMed",
        "lat": 33.978852,
        "lng": -118.089846,
        "addr": "9406 Washington Blvd Pico Rivera",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical", "Dental"]
    },
    {
        "name": "AltaMed Pomona PACE",
        "company": "AltaMed",
        "lat": 34.089656,
        "lng": -117.751266,
        "addr": "2277 N Garey Ave Pomona",
        "cat": "PACE",
        "open": "08:00",
        "close": "17:00",
        "services": ["PACE"]
    },
    {
        "name": "AltaMed Retail Clinic Olympic",
        "company": "AltaMed",
        "lat": 34.052708,
        "lng": -118.282864,
        "addr": "2323 W Olympic Blvd Los Angeles",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed Santa Ana Main",
        "company": "AltaMed",
        "lat": 33.756890,
        "lng": -117.868001,
        "addr": "1400 N Main St",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical", "Dental", "Pharmacy"]
    },
    {
        "name": "AltaMed Santa Ana Sunflower",
        "company": "AltaMed",
        "lat": 33.696524,
        "lng": -117.91807,
        "addr": "3601 W Sunflower Ave Santa Ana",
        "cat": "PACE",
        "open": "08:00",
        "close": "17:00",
        "services": ["PACE", "Medical"]
    },
    {
        "name": "AltaMed South Gate",
        "company": "AltaMed",
        "lat": 33.954263,
        "lng": -118.184678,
        "addr": "8627 Atlantic Ave. South Gate",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical", "Dental", "Pharmacy"]
    },
    {
        "name": "AltaMed South LA PACE",
        "company": "AltaMed",
        "lat": 33.945282,
        "lng": -118.241316,
        "addr": "1776 E. Century Blvd. Los Angeles",
        "cat": "PACE",
        "open": "08:00",
        "close": "17:00",
        "services": ["PACE"]
    },
    {
        "name": "AltaMed Walnut Park PACE",
        "company": "AltaMed",
        "lat": 33.970350,
        "lng": -118.232781,
        "addr": "7716 Alameda St Walnut Park",
        "cat": "PACE",
        "open": "08:00",
        "close": "17:00",
        "services": ["PACE", "Medical"]
    },
    {
        "name": "AltaMed West Covina - Sunset",
        "company": "AltaMed",
        "lat": 34.059845,
        "lng": -117.947078,
        "addr": "1300 S. Sunset Ave West Covina",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed West Covina Amar - Viva Gold",
        "company": "AltaMed",
        "lat": 34.029357,
        "lng": -117.912794,
        "addr": "1536 E Amar Rd West Covina",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical"]
    },
    {
        "name": "AltaMed West Covina PACE",
        "company": "AltaMed",
        "lat": 34.058983,
        "lng": -117.935212,
        "addr": "933 S Glendora Ave West Covina",
        "cat": "PACE",
        "open": "08:00",
        "close": "17:00",
        "services": ["PACE"]
    },
    {
        "name": "AltaMed Westlake & 3rd Street",
        "company": "AltaMed",
        "lat": 34.062454,
        "lng": -118.273422,
        "addr": "2100 West 3rd Street Los Angeles",
        "cat": "Medical",
        "open": "08:00",
        "close": "17:00",
        "services": ["Medical", "Dental"]
    },
    {
        "name": "San Antonio Regional Hospital",
        "company": "San Antonio Regional Hospital",
        "lat": 34.101611,
        "lng": -117.638866,
        "addr": "999 San Bernardino Rd, Upland, CA 91786",
        "cat": "Admin",
        "open": "00:00",
        "close": "23:59",
        "services": ["Emergency", "Surgery", "Inpatient Care"]
    },
    {
        "name": "TD SYNNEX",
        "company": "Pickup/Deliveries",
        "lat": 33.979230,
        "lng": -117.618728,
        "addr": "15065 Flight Ave, Chino, CA 91708",
        "cat": "Admin",
        "open": "08:00",
        "close": "17:00",
        "services": ["IT Distribution", "Logistics", "Warehouse"]
    },
    {
        "name": "Ingram Micro",
        "company": "Pickup/Deliveries",
        "lat": 34.009456,
        "lng": -117.554215,
        "addr": "12510 Micro Dr, Eastvale, CA 91752",
        "cat": "Admin",
        "open": "08:30",
        "close": "17:30",
        "services": ["Technology Solutions", "Logistics", "Distribution"]
    },
    {
        "name": "East Valley Community Health",
        "company": "East Valley",
        "lat": 34.067330,
        "lng": -117.925261,
        "addr": "420 S Glendora Ave, West Covina, CA 91790",
        "cat": "Medical",
        "open": "08:00",
        "close": "19:00",
        "services": ["Pharmacy", "Medical"]
    }
];
